spring.application.name=WiselySplitServer
#configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3308/WiselySplitDB}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=${PORT:8080}


security.jwt.secret=${JWT_SECRET:MySuperSecretKeyThatIsAtLeast32CharactersLong!}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}


google.client.id=${GOOGLE_CLIENT_ID:212945824367-58b5ba65qlbb6rii815magd8ug3cj32u.apps.googleusercontent.com}

# Gmail SMTP settings
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=h.v.patel029@gmail.com
#spring.mail.password=uqjdxjqginndkhsn
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Mailtrap SMTP settings
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=4d57e0cf4c204b
#spring.mail.password=931e0a5200bc07
#spring.mail.protocol=smtp
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Deplyoment SMTP settings
spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USER:4d57e0cf4c204b}
spring.mail.password=${MAIL_PASS:931e0a5200bc07}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#cloudinary.cloud_name=dwq5yfjsd
#cloudinary.api_key=531447216578187
#cloudinary.api_secret=SBB93ZqD5F1ppSx6ykB_VGSJ87w
#cloudinary.default_photo_link=https://res.cloudinary.com/dwq5yfjsd/image/upload/v1758920140/default-avatar-profile_esweq0.webp

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:dwq5yfjsd}
cloudinary.api_key=${CLOUDINARY_API_KEY:531447216578187}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:SBB93ZqD5F1ppSx6ykB_VGSJ87w}
cloudinary.default_photo_link=${CLOUDINARY_DEFAULT_PHOTO:https://res.cloudinary.com/dwq5yfjsd/image/upload/v1758920140/default-avatar-profile_esweq0.webp}
