spring.application.name=WiselySplitServer
#configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.initialization-fail-timeout=20000

server.port=${PORT}


security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS}


google.client.id=${GOOGLE_CLIENT_ID}

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mailtrap.api_key=${MAILTRAP_API_KEY}
mailtrap.api_url=${MAIL_API_URL}
mailtrap.sender_email=${MAIL_SENDER_EMAIL}
mailtrap.sender_name=${MAIL_SENDER_NAME}

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
cloudinary.default_photo_link=${CLOUDINARY_DEFAULT_PHOTO}

stripe.secret_key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

frontend.hosting_url=${FRONTEND_HOSTING_URL}