spring.application.name=WiselySplitServer
#configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3308/WiselySplitDB
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

security.jwt.secret=MySuperSecretKeyThatIsAtLeast32CharactersLong!
security.jwt.expiration-ms=3600000

google.client.id=212945824367-58b5ba65qlbb6rii815magd8ug3cj32u.apps.googleusercontent.com

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=h.v.patel029@gmail.com
#spring.mail.password=uqjdxjqginndkhsn
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Mailtrap SMTP settings
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=4d57e0cf4c204b
spring.mail.password=931e0a5200bc07
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud_name=dwq5yfjsd
cloudinary.api_key=531447216578187
cloudinary.api_secret=SBB93ZqD5F1ppSx6ykB_VGSJ87w